(function () {
  const messages = {
    en: {
      global: { homeSubtitle: "Birth chart readings", readingSubtitle: "Reading room", accountSubtitle: "Member account", language: "Language" },
      nav: { readings: "Readings", chart: "Chart", glossary: "Glossary", trust: "Trust", newChart: "New Chart", readingRoom: "Reading Room" },
      auth: { login: "Login", account: "Account", eyebrow: "Member login", title: "Sign in when you want to keep this reading.", note: "Continue with Google or email.", google: "Continue with Google", email: "Email", password: "Password", signIn: "Sign in", create: "Create account", reset: "Reset password", close: "Close login", opening: "Opening Google login...", resetSent: "Password reset email sent.", emailFirst: "Enter your email first.", passwordFirst: "Enter your password." },
      home: { eyebrow: "Birth data -> corrected chart -> a reading that feels personal", title: "A Korean Saju reading that explains the chart while it reads you.", intro: "SajuPop turns your birth date, time, and place into a corrected Four Pillars chart, then explains what the unfamiliar markers may feel like in real life.", proofChart: "Manse-calculated", proofVoice: "Native-feeling voice", proofPrivacy: "Private by default" },
      form: { title: "Birth Setup", correctionReady: "Time correction ready", name: "Name", date: "Date", time: "Time", country: "Birth Country", city: "Birth City", cityPlaceholder: "Type any city", calendar: "Calendar", gregorian: "Gregorian", lunar: "Lunar", unknown: "Unknown", accuracy: "Accuracy", exact: "Exact time", approximate: "Approximate", unknownTime: "Unknown time", correctionIncluded: "Location correction included", correctionNote: "City and country are used quietly in the background. No timezone math to figure out.", continue: "Read My Chart" },
      products: { eyebrow: "Pick a reading", title: "Start small. Keep the detail.", birthTitle: "$0.99 Birth Chart", birthBody: "Personality, money, work, love, family, location, and practical actions.", oneStar: "1 Star Credit", unlock: "Login to Unlock", compatTitle: "Compatibility Remix", compatBody: "Partners, friends, founders, roommates, and every in-between.", compare: "Login to Compare", cycleTitle: "10-Year Luck Cycle", cycleBody: "The larger rhythm: when to push, pause, move, build, or reset.", partlyFree: "Partly Free", open: "Login to Open", dateTitle: "Lucky Date Picker", dateBody: "Choose dates for launches, moves, weddings, contracts, and openings.", pick: "Login to Pick", yearTitle: "Year Ahead", yearBody: "Annual theme, monthly rhythm, pressure points, and useful windows.", view: "Login to View", askTitle: "Ask The Reader", askBody: "Ask a follow-up in your language after the report.", oneMoon: "1 Moon Credit", askCta: "Login to Ask" },
      filters: { all: "All", saju: "Saju", timing: "Timing", ask: "Ask", basics: "Basics", stars: "Stars", links: "Links" },
      chart: { eyebrow: "Manse calendar view", title: "See the chart before you read the interpretation.", meta: "This is the shape SajuPop reads from your birth data.", tapTerm: "Tap a chart chip to see what it means in everyday language." },
      pillar: { hour: "Hour", day: "Day", month: "Month", year: "Year", private: "Private self", identity: "Identity", social: "Social role", roots: "Roots", inner: "inner room", center: "center", season: "season", origin: "origin" },
      terms: { dayMaster: "Day Master", hiddenStems: "Hidden Stems", tenGods: "Ten Gods", stars: "Symbolic Stars", harm: "Zi-Wei Harm", ghostGate: "Ghost Gate" },
      termHelp: { dayMaster: "The Day Master is the center of the chart. Work, money, love, pressure, and support are read in relation to it.", hiddenStems: "Hidden Stems are the inner layer inside each ground sign: present, but not always visible at first.", tenGods: "Ten Gods are relationship labels for self, peers, expression, money, authority, pressure, and support.", stars: "Symbolic Stars add texture such as charm, movement, mentors, precision, or emotional intensity.", harm: "A Harm marker points to a subtle mismatch. It is quieter than a clash, but can drain energy over time.", ghostGate: "Ghost Gate is associated with sharp intuition and thought loops. Used well, it can become creative perception." },
      explain: { eyebrow: "A visual way in", title: "New to Saju? Start with shape, color, and role.", pillarsTitle: "Four Pillars", pillarsBody: "Each pillar has a sky sign and a ground sign. The Day Master is the center; every other marker is read in relation to it.", elementsTitle: "Five Elements", elementsBody: "Elements become moods, habits, work styles, relationship needs, and timing patterns. Color helps you spot the balance at a glance.", linksTitle: "Links Under The Chart", linksBody: "These links help explain where life feels easy, tense, magnetic, repetitive, or emotionally complicated." },
      element: { wood: "Wood", fire: "Fire", earth: "Earth", metal: "Metal", water: "Water", growth: "growth", spark: "spark", ground: "ground", edge: "edge", flow: "flow" },
      link: { combination: "Combination", clash: "Clash", harm: "Harm", penalty: "Penalty", ghostGate: "Ghost Gate" },
      glossary: { eyebrow: "Built-in translation", title: "Technical terms, followed by words you already know.", manseTitle: "Manse Calendar", manseBody: "The calendar system that turns birth data into year, month, day, and hour pillars.", dayMasterBody: "The sky sign of the Day Pillar and the reference point for the whole reading.", wealthTitle: "Stable Wealth", wealthBody: "Routine income, budgeting, tangible assets, reliability, and practical resource sense.", resourceTitle: "Mystic Resource", resourceBody: "Intuition, unusual learning, deep analysis, private imagination, and thought loops.", needleTitle: "Needle Star", needleBody: "Precise observation and sharp language, often useful in technical or detail-heavy work.", nobleTitle: "Heavenly Noble", nobleBody: "Mentors, timely help, and support that tends to appear when it matters.", comboBody: "Two signs cooperate and may lean toward another element under the right conditions.", clashBody: "Opposition that may show up as conflict, movement, distance, or necessary change." },
      trust: { eyebrow: "Clear about what this is", title: "A Korean tradition for reflection, not a scientific verdict.", body: "SajuPop explains how the chart was calculated, keeps birth data private, and avoids medical, legal, psychological, or financial certainty.", item1: "Birthplace-aware calculation", item2: "Plain-language explanations", item3: "Cultural context included", item4: "No deterministic fear claims", item5: "Private saved charts" },
      bottom: { home: "Home", add: "Add", shop: "Shop", learn: "Learn", account: "Account" },
      loading: { eyebrow: "Reading your chart", title: "Starting with the place and time you were born.", intro: "First we build the Manse chart. Then we look for the patterns that deserve careful words.", estimate: "Usually takes", estimateValue: "about 1-3 min", elapsed: "Elapsed", seconds: "sec", stage1: "Correct birth time", stage2: "Build Four Pillars", stage3: "Trace the chart patterns", stage4: "Write your interpretation", stage5: "Choose the words with care", long: "This one is taking a little longer, but your reading is still being written." },
      result: { eyebrow: "Your reading", ready: "Your SajuPop reading is ready.", overview: "At a glance", chart: "Your chart", reading: "Full reading", actions: "Small actions", seen: "What feels seen", pattern: "Core pattern", move: "Try this first", center: "Center of the chart", elementBalance: "Element balance", plain: "In everyday words", strongest: "Strongest", quietest: "Quietest", helpful: "Helpful", location: "Birthplace", noLinks: "No major chart link detected", why: "Why the chart says this", actionsTitle: "Small things that may help", saveTitle: "Keep this reading when it feels worth keeping.", saveBody: "Login only when you want to save it, unlock the full report, or buy credits.", saveCta: "Login to save or continue", disclaimer: "Saju is a traditional interpretive system for reflection and entertainment. This reading is not medical, legal, financial, or psychological advice.", retryTitle: "The reading stopped before it was finished.", retry: "Try again", noData: "No birth data", noDataTitle: "Start with your birth details.", noDataBody: "The reading room needs a date, time, and place before it can build your chart.", start: "Go to Birth Setup", marker: "Chart marker", loudQuiet: "what is loud / what needs support", remedy: "habits that make the chart easier to live", relation: "why a pattern may feel smooth, tense, magnetic, or complex", groupSelf: "Understanding your inner pattern", groupChoices: "Choices in the real world", groupRelationships: "How you relate", groupDirection: "Environment and next steps", categoryCore: "Core temperament", categoryElements: "Five Element balance", categoryIdentity: "Identity and inner standards", categoryBlindSpot: "A pattern to watch", categoryEffort: "Effort worth recognizing", categoryPersonality: "Personality and emotion", categoryCareer: "Career and work", categoryMoney: "Money and resources", categoryLove: "Love and intimacy", categoryFamily: "Family and boundaries", categoryFriends: "Friends and social life", categoryEnvironment: "Environment and lifestyle", categoryPractice: "Practical experiments" },
      account: { eyebrow: "Your SajuPop space", title: "Your readings, whenever you want to return to them.", body: "You can read first without an account. Sign in only to save a chart, unlock checkout, or keep your history.", loginTitle: "Save this for later", loginBody: "Use Google or email when a reading feels worth keeping.", vault: "Reading Vault", vaultBody: "Saved charts and unlocked reports will stay together here.", wallet: "Credit Wallet", walletBody: "Star and Moon Credits will appear here after checkout is connected.", privacy: "Private Profile", privacyBody: "Each account can only access its own member record and saved data.", credits: "Credits", starCredits: "Star Credits", moonCredits: "Moon Credits", creditsBody: "Credits update here after a completed payment.", membership: "Membership", membershipBody: "Your plan and connected sign-in methods.", plan: "Plan", providers: "Providers", saved: "Saved Readings", vaultEmpty: "Your saved readings will appear here.", signOut: "Sign out" },
      errors: { generic: "Something went wrong. Please try again.", config: "Login is connected, but Firebase Authentication still needs to be enabled.", method: "This sign-in method is not enabled yet.", popup: "The login popup was blocked. Allow popups and try again.", domain: "This test address is not authorized for Google login yet.", credentials: "That email or password does not match.", exists: "This email already has an account. Try signing in instead." }
    },
    ko: {
      global: { homeSubtitle: "사주 풀이", readingSubtitle: "사주 풀이방", accountSubtitle: "내 사주 보관함", language: "언어" },
      nav: { readings: "사주 메뉴", chart: "만세력", glossary: "용어 풀이", trust: "안내", newChart: "새 사주", readingRoom: "풀이방" },
      auth: { login: "로그인", account: "내 계정", eyebrow: "회원 로그인", title: "이 풀이를 간직하고 싶을 때 로그인하세요.", note: "Google 또는 이메일로 계속할 수 있어요.", google: "Google로 계속하기", email: "이메일", password: "비밀번호", signIn: "로그인", create: "회원가입", reset: "비밀번호 찾기", close: "로그인 닫기", opening: "Google 로그인 창을 여는 중이에요...", resetSent: "비밀번호 재설정 메일을 보냈어요.", emailFirst: "이메일을 먼저 입력해 주세요.", passwordFirst: "비밀번호를 입력해 주세요." },
      home: { eyebrow: "출생 정보 -> 보정된 만세력 -> 나에게 와닿는 풀이", title: "사주를 풀어드릴게요. 어려운 말보다, 나에게 와닿는 말로요.", intro: "태어난 날짜와 시간, 장소를 만세력으로 계산한 뒤 낯선 사주 용어가 실제 삶에서는 어떤 모습으로 드러나는지 차근차근 풀어드려요.", proofChart: "만세력 기반 계산", proofVoice: "번역투 없는 말투", proofPrivacy: "기본 비공개" },
      form: { title: "출생 정보", correctionReady: "출생지 보정 포함", name: "이름", date: "생년월일", time: "태어난 시간", country: "출생 국가", city: "출생 도시", cityPlaceholder: "도시 이름을 입력하세요", calendar: "달력", gregorian: "양력", lunar: "음력", unknown: "모름", accuracy: "시간 정확도", exact: "정확함", approximate: "대략 알고 있음", unknownTime: "시간을 모름", correctionIncluded: "출생지에 맞춰 알아서 계산해요", correctionNote: "시차나 보정값은 직접 계산하지 않아도 돼요. 국가와 도시만 알려주세요.", continue: "내 사주 풀이 보기" },
      products: { eyebrow: "보고 싶은 풀이", title: "부담 없이 시작하고, 내용은 충분하게.", birthTitle: "990원 사주", birthBody: "성격, 재물, 직업, 연애, 가족, 잘 맞는 환경과 생활 팁까지 풀어봐요.", oneStar: "별 1개", unlock: "로그인하고 열기", compatTitle: "궁합 풀이", compatBody: "연인뿐 아니라 친구, 동업자, 룸메이트 사이도 함께 볼 수 있어요.", compare: "로그인하고 궁합 보기", cycleTitle: "10년 대운", cycleBody: "밀어붙일 때와 쉬어갈 때, 옮길 때와 쌓아갈 때를 큰 흐름으로 봐요.", partlyFree: "일부 무료", open: "로그인하고 보기", dateTitle: "좋은 날 찾기", dateBody: "이사, 결혼, 계약, 개업처럼 중요한 일에 어울리는 날을 골라봐요.", pick: "로그인하고 날짜 보기", yearTitle: "올해 운세", yearBody: "한 해의 주제와 월별 흐름, 조심할 때와 움직이기 좋은 때를 살펴봐요.", view: "로그인하고 보기", askTitle: "사주 상담", askBody: "풀이를 읽고 남은 질문을 편한 말로 이어서 물어보세요.", oneMoon: "달 1개", askCta: "로그인하고 질문하기" },
      filters: { all: "전체", saju: "사주", timing: "운세·택일", ask: "상담", basics: "기본", stars: "신살", links: "합·충·해" },
      chart: { eyebrow: "만세력", title: "해석을 읽기 전에, 어떤 사주인지 먼저 보여드려요.", meta: "출생 정보를 넣으면 아래와 같은 만세력을 계산해요.", tapTerm: "궁금한 표시를 누르면 일상적인 말로 뜻을 알려드려요." },
      pillar: { hour: "시주", day: "일주", month: "월주", year: "연주", private: "내밀한 나", identity: "나의 중심", social: "사회 속 역할", roots: "뿌리와 환경", inner: "속마음", center: "중심", season: "사회", origin: "뿌리" },
      terms: { dayMaster: "일간", hiddenStems: "지장간", tenGods: "십신", stars: "신살", harm: "자미해", ghostGate: "귀문관살" },
      termHelp: { dayMaster: "일간은 사주에서 나를 뜻하는 중심이에요. 재물, 직업, 연애, 압박과 도움도 모두 이 기준에서 읽어요.", hiddenStems: "지장간은 지지 안에 숨어 있는 기운이에요. 겉으로 바로 보이지 않지만 속마음과 잠재력을 읽을 때 살펴봐요.", tenGods: "십신은 나와 다른 기운의 관계를 붙인 이름이에요. 친구, 표현력, 재물, 책임, 압박, 도움처럼 풀어볼 수 있어요.", stars: "신살은 매력, 이동, 귀인, 날카로운 감각, 예민함처럼 사주에 결을 더하는 보조 표시예요.", harm: "해는 크게 부딪히기보다 미묘하게 어긋나는 관계를 뜻해요. 작은 서운함이나 피로가 쌓이는 모습으로 나타나기도 해요.", ghostGate: "귀문관살은 직감이 빠르고 생각이 깊은 흐름과 연결돼요. 잘 쓰면 남들이 놓친 부분을 알아채는 감각이 됩니다." },
      explain: { eyebrow: "눈으로 먼저 이해하기", title: "사주가 처음이라면 역할, 색, 모양부터 보면 쉬워요.", pillarsTitle: "네 개의 기둥", pillarsBody: "각 기둥에는 위의 글자와 아래의 글자가 있어요. 나를 뜻하는 일간을 중심에 두고, 나머지 표시와의 관계를 읽습니다.", elementsTitle: "오행", elementsBody: "오행은 물건 이름에 그치지 않아요. 감정, 습관, 일하는 방식, 관계에서 필요한 것과 시기의 흐름으로 이어져요.", linksTitle: "사주 아래의 관계 표시", linksBody: "합, 충, 해, 형 같은 표시는 어느 부분이 편안하고 팽팽한지, 무엇이 자꾸 반복되는지 이해하는 단서예요." },
      element: { wood: "목", fire: "화", earth: "토", metal: "금", water: "수", growth: "성장", spark: "열정", ground: "안정", edge: "결단", flow: "감수성" },
      link: { combination: "합", clash: "충", harm: "해", penalty: "형", ghostGate: "귀문" },
      glossary: { eyebrow: "용어를 바로 풀어서", title: "낯선 명리 용어 옆에, 이해하기 쉬운 뜻을 붙였어요.", manseTitle: "만세력", manseBody: "출생 정보를 연주, 월주, 일주, 시주로 바꾸는 역법이에요.", dayMasterBody: "일주의 천간으로, 사주에서 나를 읽는 기준점이에요.", wealthTitle: "정재", wealthBody: "꾸준한 수입, 저축, 현실 감각, 책임감과 안정적인 자원 관리에 가까워요.", resourceTitle: "편인", resourceBody: "직감, 남다른 배움, 깊은 분석, 혼자만의 상상과 생각이 많아지는 흐름이에요.", needleTitle: "현침살", needleBody: "관찰과 말이 정교한 기운으로, 기술이나 세밀한 일에서 장점이 되기도 해요.", nobleTitle: "천을귀인", nobleBody: "필요한 순간에 도움을 주는 사람이나 기회와 연결해서 보는 귀인성이에요.", comboBody: "두 글자가 서로 힘을 모으고, 조건에 따라 다른 오행의 흐름을 만들기도 해요.", clashBody: "서로 마주 보는 기운으로, 갈등뿐 아니라 이동과 변화가 필요한 때를 뜻하기도 해요." },
      trust: { eyebrow: "분명하게 알려드려요", title: "사주는 나를 돌아보는 전통이지, 삶을 단정하는 과학이 아니에요.", body: "SajuPop은 계산 근거를 보여주고 출생 정보를 조심히 다뤄요. 건강, 법률, 심리, 재정 문제를 사주로 단정하지 않습니다.", item1: "출생지를 반영한 계산", item2: "쉬운 말로 붙인 설명", item3: "한국 사주의 문화적 맥락", item4: "불안을 부추기는 단정 금지", item5: "나만 볼 수 있는 보관함" },
      bottom: { home: "홈", add: "사주 추가", shop: "메뉴", learn: "용어", account: "내 정보" },
      loading: { eyebrow: "사주를 읽고 있어요", title: "태어난 장소와 시간부터 차근차근 맞춰볼게요.", intro: "먼저 만세력을 만들고, 그 안에서 여러 번 겹쳐 보이는 흐름을 찾습니다. 서두르지 않고 말까지 다듬어 전해드릴게요.", estimate: "보통", estimateValue: "1~3분 정도", elapsed: "기다린 시간", seconds: "초", stage1: "출생 시간 맞추기", stage2: "네 기둥 세우기", stage3: "사주의 흐름 살펴보기", stage4: "영역별 풀이 쓰기", stage5: "마음에 닿는 말로 다듬기", long: "조금 오래 걸리고 있지만 멈춘 건 아니에요. 마지막 문장을 다듬고 있어요." },
      result: { eyebrow: "나의 사주 풀이", ready: "사주 풀이가 완성됐어요.", overview: "먼저 볼 내용", chart: "내 만세력", reading: "전체 풀이", actions: "생활 팁", seen: "가장 먼저 알아줄 마음", pattern: "눈에 띄는 흐름", move: "오늘 해볼 일", center: "사주의 중심", elementBalance: "오행의 균형", plain: "쉬운 말로 보면", strongest: "두드러진 기운", quietest: "부족한 기운", helpful: "도움 되는 기운", location: "출생지", noLinks: "크게 두드러진 관계 표시는 없어요", why: "이렇게 읽은 이유", actionsTitle: "부담 없이 해볼 수 있는 것", saveTitle: "다시 읽고 싶은 풀이만 보관해도 돼요.", saveBody: "저장하거나 전체 풀이를 결제할 때만 로그인하세요.", saveCta: "로그인하고 저장하기", disclaimer: "사주는 성찰과 재미를 위한 전통적인 해석 체계입니다. 이 풀이는 의료, 법률, 재정, 심리 상담을 대신하지 않습니다.", retryTitle: "풀이가 끝나기 전에 잠시 멈췄어요.", retry: "다시 시도하기", noData: "출생 정보가 없어요", noDataTitle: "출생 정보부터 입력해 주세요.", noDataBody: "사주를 계산하려면 태어난 날짜와 시간, 장소가 필요해요.", start: "출생 정보 입력하기", marker: "사주 표시", loudQuiet: "두드러진 것과 돌봄이 필요한 것", remedy: "이 기운을 편하게 쓰는 생활 습관", relation: "편안함과 긴장, 끌림과 반복이 생기는 이유", groupSelf: "나를 이해하는 흐름", groupChoices: "현실에서 내리는 선택", groupRelationships: "사람을 대하는 방식", groupDirection: "생활 환경과 다음 방향", categoryCore: "핵심 기질", categoryElements: "오행의 균형", categoryIdentity: "내면과 정체성", categoryBlindSpot: "놓치기 쉬운 점", categoryEffort: "내가 해온 노력", categoryPersonality: "성격과 감정", categoryCareer: "진로와 일", categoryMoney: "재물과 소비", categoryLove: "연애와 친밀감", categoryFamily: "가족과 경계", categoryFriends: "대인관계", categoryEnvironment: "환경과 생활", categoryPractice: "실천 가이드" },
      account: { eyebrow: "내 SajuPop", title: "마음에 남은 풀이를, 다시 보고 싶을 때 꺼내보세요.", body: "회원가입 없이 먼저 읽을 수 있어요. 풀이를 저장하거나 결제하고 싶을 때만 로그인하면 됩니다.", loginTitle: "나중에 다시 보기", loginBody: "간직하고 싶은 풀이가 생겼다면 Google 또는 이메일로 로그인하세요.", vault: "사주 보관함", vaultBody: "저장한 만세력과 결제한 풀이를 한곳에 모아둘 수 있어요.", wallet: "이용권", walletBody: "결제가 연결되면 별과 달 이용권이 여기에 표시돼요.", privacy: "비공개 프로필", privacyBody: "각 계정은 본인의 회원 정보와 저장 데이터만 볼 수 있어요.", credits: "이용권", starCredits: "별 이용권", moonCredits: "달 이용권", creditsBody: "결제가 끝나면 이용권 수량이 이곳에 반영돼요.", membership: "회원 정보", membershipBody: "이용 등급과 연결된 로그인 방법을 확인할 수 있어요.", plan: "이용 등급", providers: "로그인 방법", saved: "저장한 풀이", vaultEmpty: "저장한 풀이가 생기면 이곳에서 다시 볼 수 있어요.", signOut: "로그아웃" },
      errors: { generic: "잠시 문제가 생겼어요. 다시 시도해 주세요.", config: "로그인 연결은 됐지만 Firebase에서 인증 기능을 아직 켜지 않았어요.", method: "아직 사용할 수 없는 로그인 방법이에요.", popup: "로그인 창이 차단됐어요. 팝업을 허용한 뒤 다시 시도해 주세요.", domain: "이 테스트 주소는 아직 Google 로그인 허용 주소에 등록되지 않았어요.", credentials: "이메일 또는 비밀번호가 맞지 않아요.", exists: "이미 가입된 이메일이에요. 로그인으로 들어가 주세요." }
    },
    "zh-CN": {
      global: { homeSubtitle: "四柱命理解读", readingSubtitle: "解读室", accountSubtitle: "个人空间", language: "语言" },
      nav: { readings: "解读项目", chart: "命盘", glossary: "术语", trust: "说明", newChart: "新命盘", readingRoom: "解读室" },
      auth: { login: "登录", account: "账户", eyebrow: "会员登录", title: "想保存这份解读时再登录就好。", note: "可使用 Google 或邮箱继续。", google: "使用 Google 继续", email: "邮箱", password: "密码", signIn: "登录", create: "注册账户", reset: "重置密码", close: "关闭登录", opening: "正在打开 Google 登录...", resetSent: "密码重置邮件已发送。", emailFirst: "请先填写邮箱。", passwordFirst: "请输入密码。" },
      home: { eyebrow: "出生信息 -> 校正命盘 -> 真正贴近你的解读", title: "把韩国四柱讲清楚，也把你的感受放在心上。", intro: "SajuPop 会根据出生日期、时间和地点排出四柱，再把陌生的十神、神煞与五行关系，讲成现实生活里听得懂的话。", proofChart: "万年历排盘", proofVoice: "自然母语表达", proofPrivacy: "默认私密" },
      form: { title: "出生信息", correctionReady: "已包含地点校正", name: "名字", date: "出生日期", time: "出生时间", country: "出生国家", city: "出生城市", cityPlaceholder: "输入任意城市", calendar: "历法", gregorian: "公历", lunar: "农历", unknown: "不清楚", accuracy: "时间准确度", exact: "准确时间", approximate: "大概时间", unknownTime: "不知道时间", correctionIncluded: "地点校正已包含", correctionNote: "只需选择国家和城市，时区与时间校正会在后台完成。", continue: "解读我的命盘" },
      products: { eyebrow: "选择解读", title: "轻松开始，内容依然细致。", birthTitle: "$0.99 出生命盘", birthBody: "性格、财富、工作、感情、家庭、适合的环境与实际建议。", oneStar: "1 枚星星", unlock: "登录后解锁", compatTitle: "关系合盘", compatBody: "适合伴侣、朋友、合伙人、室友，以及各种亲密关系。", compare: "登录后合盘", cycleTitle: "十年大运", cycleBody: "看清何时推进、停一停、搬迁、积累或重新开始。", partlyFree: "部分免费", open: "登录后查看", dateTitle: "择日", dateBody: "为开业、搬家、婚礼、签约等重要事情选择合适日期。", pick: "登录后择日", yearTitle: "流年运势", yearBody: "年度主题、每月节奏、压力点与适合行动的时间。", view: "登录后查看", askTitle: "继续问", askBody: "读完报告后，用你的语言追问最在意的事。", oneMoon: "1 枚月亮", askCta: "登录后提问" },
      filters: { all: "全部", saju: "四柱", timing: "运势·择日", ask: "提问", basics: "基础", stars: "神煞", links: "关系" },
      chart: { eyebrow: "万年历命盘", title: "先看命盘，再读解读。", meta: "SajuPop 会从你的出生信息排出这样的四柱命盘。", tapTerm: "点一下标记，就能看到日常语言里的意思。" },
      pillar: { hour: "时柱", day: "日柱", month: "月柱", year: "年柱", private: "私下的自己", identity: "自我核心", social: "社会角色", roots: "家庭根基", inner: "内在", center: "中心", season: "环境", origin: "根源" },
      terms: { dayMaster: "日主", hiddenStems: "藏干", tenGods: "十神", stars: "神煞", harm: "子未害", ghostGate: "鬼门" },
      termHelp: { dayMaster: "日主是命盘的中心。工作、财富、感情、压力与支持，都要看它们和日主的关系。", hiddenStems: "藏干是地支内部的气，代表存在却不一定马上显露的情绪、能力与倾向。", tenGods: "十神是关系标签，用来理解同伴、表达、财富、责任、压力与支持。", stars: "神煞为命盘增加细节，例如魅力、移动、贵人、敏锐度或情绪强度。", harm: "害代表细微的不协调。它不像冲那么直接，却可能慢慢消耗精力。", ghostGate: "鬼门常与敏锐直觉和反复思考有关。用得好，会成为很强的洞察力。" },
      explain: { eyebrow: "先用眼睛理解", title: "第一次看四柱？先看角色、颜色和形状。", pillarsTitle: "四柱", pillarsBody: "每一柱都有天干与地支。解读以日主为中心，再看其他标记与它的关系。", elementsTitle: "五行", elementsBody: "五行会变成情绪、习惯、工作方式、关系需求与时间节奏。颜色能帮助你快速看出强弱。", linksTitle: "命盘里的关系", linksBody: "合、冲、害、刑等关系，帮助理解哪里顺畅、紧张、有吸引力，或总在重复。" },
      element: { wood: "木", fire: "火", earth: "土", metal: "金", water: "水", growth: "生长", spark: "热情", ground: "稳定", edge: "决断", flow: "感受" },
      link: { combination: "合", clash: "冲", harm: "害", penalty: "刑", ghostGate: "鬼门" },
      glossary: { eyebrow: "术语随手翻译", title: "保留专业词，也给你熟悉的解释。", manseTitle: "万年历", manseBody: "把出生信息换算成年、月、日、时四柱的历法系统。", dayMasterBody: "日柱的天干，也是整份命理解读的参照点。", wealthTitle: "正财", wealthBody: "稳定收入、预算、实物资产、可靠性与务实的资源管理。", resourceTitle: "偏印", resourceBody: "直觉、独特学习方式、深入分析、私人想象与思虑过多。", needleTitle: "悬针煞", needleBody: "细致观察与锋利表达，常在技术性或重视细节的工作中成为优势。", nobleTitle: "天乙贵人", nobleBody: "在关键时刻出现的帮助、导师或机会。", comboBody: "两个标记彼此配合，在特定条件下也可能偏向另一种五行。", clashBody: "相对的力量，可能表现为冲突、移动、距离或必须发生的改变。" },
      trust: { eyebrow: "把边界说清楚", title: "这是用来认识自己的韩国传统，不是科学判决。", body: "SajuPop 会说明命盘如何计算，谨慎处理出生信息，也不会对医疗、法律、心理或财务问题作确定判断。", item1: "考虑出生地点的排盘", item2: "日常语言解释", item3: "包含文化背景", item4: "不制造宿命恐惧", item5: "私密保存命盘" },
      bottom: { home: "首页", add: "排盘", shop: "项目", learn: "术语", account: "我的" },
      loading: { eyebrow: "正在读你的命盘", title: "先从出生的时间和地点开始。", intro: "我们会先排出四柱，再寻找反复出现的模式，最后认真选择表达方式。", estimate: "通常需要", estimateValue: "约 1-3 分钟", elapsed: "已等待", seconds: "秒", stage1: "校正出生时间", stage2: "排出四柱", stage3: "梳理命盘关系", stage4: "撰写各项解读", stage5: "把语气调整得更贴近你", long: "这次稍微久一点，但没有停住。正在整理最后的表达。" },
      result: { eyebrow: "你的四柱解读", ready: "你的 SajuPop 解读完成了。", overview: "先看重点", chart: "你的命盘", reading: "完整解读", actions: "生活建议", seen: "最想先理解你的地方", pattern: "核心模式", move: "先试试这个", center: "命盘中心", elementBalance: "五行比例", plain: "换成日常语言", strongest: "最明显", quietest: "最需要照顾", helpful: "有帮助", location: "出生地", noLinks: "没有特别突出的关系标记", why: "为什么这样解读", actionsTitle: "可以轻松尝试的小事", saveTitle: "觉得值得，就把这份解读留下来。", saveBody: "只有保存、解锁完整报告或购买点数时才需要登录。", saveCta: "登录并保存", disclaimer: "四柱是用于自我观察与娱乐的传统解释体系，不能代替医疗、法律、财务或心理建议。", retryTitle: "解读还没完成就暂时停下了。", retry: "再试一次", noData: "没有出生信息", noDataTitle: "请先填写出生信息。", noDataBody: "排盘需要出生日期、时间和地点。", start: "去填写出生信息", marker: "命盘标记", loudQuiet: "明显的部分与需要照顾的部分", remedy: "让这份能量更好用的习惯", relation: "顺畅、紧张、吸引与反复出现的原因", groupSelf: "理解内在模式", groupChoices: "现实中的选择", groupRelationships: "与人相处的方式", groupDirection: "生活环境与下一步", categoryCore: "核心气质", categoryElements: "五行平衡", categoryIdentity: "自我与内在标准", categoryBlindSpot: "容易忽略的地方", categoryEffort: "值得看见的努力", categoryPersonality: "性格与情绪", categoryCareer: "事业与工作", categoryMoney: "金钱与资源", categoryLove: "爱情与亲密", categoryFamily: "家庭与边界", categoryFriends: "人际关系", categoryEnvironment: "环境与生活", categoryPractice: "行动建议" },
      account: { eyebrow: "你的 SajuPop 空间", title: "想再看时，随时回来。", body: "无需注册也能先读。只有保存命盘、解锁付款或保留记录时才需要登录。", loginTitle: "保存到以后", loginBody: "遇到想留下的解读时，再用 Google 或邮箱登录。", vault: "解读收藏", vaultBody: "保存的命盘与已解锁报告会集中在这里。", wallet: "点数钱包", walletBody: "接入付款后，星星与月亮点数会显示在这里。", privacy: "私密资料", privacyBody: "每个账户只能查看自己的会员记录与保存内容。", credits: "点数", starCredits: "星星点数", moonCredits: "月亮点数", creditsBody: "付款完成后，点数会更新在这里。", membership: "会员信息", membershipBody: "查看方案与已连接的登录方式。", plan: "方案", providers: "登录方式", saved: "已保存解读", vaultEmpty: "保存的解读会出现在这里。", signOut: "退出登录" },
      errors: { generic: "出了点问题，请再试一次。", config: "登录已连接，但 Firebase Authentication 尚未启用。", method: "这种登录方式还未启用。", popup: "登录窗口被拦截，请允许弹窗后重试。", domain: "这个测试地址还没有加入 Google 登录授权域名。", credentials: "邮箱或密码不正确。", exists: "这个邮箱已经注册，请直接登录。" }
    },
    es: {
      global: { homeSubtitle: "Lecturas de los Cuatro Pilares", readingSubtitle: "Sala de lectura", accountSubtitle: "Cuenta", language: "Idioma" },
      nav: { readings: "Lecturas", chart: "Carta", glossary: "Glosario", trust: "Información", newChart: "Nueva carta", readingRoom: "Sala de lectura" },
      auth: { login: "Iniciar sesión", account: "Mi cuenta", eyebrow: "Acceso de miembros", title: "Inicia sesión solo cuando quieras guardar esta lectura.", note: "Continúa con Google o correo electrónico.", google: "Continuar con Google", email: "Correo", password: "Contraseña", signIn: "Entrar", create: "Crear cuenta", reset: "Restablecer contraseña", close: "Cerrar acceso", opening: "Abriendo Google...", resetSent: "Te enviamos el correo para restablecer la contraseña.", emailFirst: "Primero escribe tu correo.", passwordFirst: "Escribe tu contraseña." },
      home: { eyebrow: "Datos de nacimiento -> carta corregida -> una lectura personal", title: "Una lectura coreana de Saju que explica la carta mientras habla de ti.", intro: "SajuPop convierte tu fecha, hora y lugar de nacimiento en una carta de Cuatro Pilares y traduce sus símbolos a situaciones que puedes reconocer en la vida diaria.", proofChart: "Cálculo Manse", proofVoice: "Voz natural", proofPrivacy: "Privado por defecto" },
      form: { title: "Datos de nacimiento", correctionReady: "Corrección horaria incluida", name: "Nombre", date: "Fecha", time: "Hora", country: "País de nacimiento", city: "Ciudad de nacimiento", cityPlaceholder: "Escribe cualquier ciudad", calendar: "Calendario", gregorian: "Gregoriano", lunar: "Lunar", unknown: "No lo sé", accuracy: "Precisión", exact: "Hora exacta", approximate: "Aproximada", unknownTime: "No sé la hora", correctionIncluded: "Incluye corrección por lugar", correctionNote: "Solo dinos el país y la ciudad. El ajuste horario se hace en segundo plano.", continue: "Leer mi carta" },
      products: { eyebrow: "Elige una lectura", title: "Empieza con poco. Recibe mucho detalle.", birthTitle: "Carta natal por $0.99", birthBody: "Personalidad, dinero, trabajo, amor, familia, entorno y acciones concretas.", oneStar: "1 crédito Estrella", unlock: "Entrar para desbloquear", compatTitle: "Compatibilidad", compatBody: "Para parejas, amistades, socios, compañeros de piso y vínculos difíciles de definir.", compare: "Entrar para comparar", cycleTitle: "Ciclo de suerte de 10 años", cycleBody: "El ritmo amplio: cuándo avanzar, parar, mudarte, construir o empezar de nuevo.", partlyFree: "Parte gratis", open: "Entrar para abrir", dateTitle: "Selector de fechas", dateBody: "Elige fechas para lanzamientos, mudanzas, bodas, contratos y aperturas.", pick: "Entrar para elegir", yearTitle: "Tu próximo año", yearBody: "Tema anual, ritmo mensual, momentos de presión y ventanas útiles.", view: "Entrar para ver", askTitle: "Pregunta al lector", askBody: "Haz una pregunta en tu idioma después de leer el informe.", oneMoon: "1 crédito Luna", askCta: "Entrar para preguntar" },
      filters: { all: "Todo", saju: "Saju", timing: "Ciclos y fechas", ask: "Preguntas", basics: "Conceptos", stars: "Estrellas", links: "Relaciones" },
      chart: { eyebrow: "Vista del calendario Manse", title: "Mira la carta antes de leer la interpretación.", meta: "Esta es la estructura que SajuPop obtiene de tus datos de nacimiento.", tapTerm: "Toca una etiqueta para verla explicada con palabras cotidianas." },
      pillar: { hour: "Hora", day: "Día", month: "Mes", year: "Año", private: "Yo privado", identity: "Identidad", social: "Rol social", roots: "Raíces", inner: "interior", center: "centro", season: "entorno", origin: "origen" },
      terms: { dayMaster: "Maestro del Día", hiddenStems: "Troncos ocultos", tenGods: "Diez Dioses", stars: "Estrellas simbólicas", harm: "Daño Zi-Wei", ghostGate: "Puerta Fantasma" },
      termHelp: { dayMaster: "El Maestro del Día es el centro de la carta. Trabajo, dinero, amor, presión y apoyo se leen según su relación con él.", hiddenStems: "Los Troncos ocultos son la capa interior de cada rama: están presentes, aunque no siempre se vean al principio.", tenGods: "Los Diez Dioses nombran relaciones como identidad, pares, expresión, dinero, autoridad, presión y apoyo.", stars: "Las Estrellas simbólicas añaden matices como encanto, movimiento, mentores, precisión o intensidad emocional.", harm: "Un Daño señala un desajuste sutil. Es menos directo que un choque, pero puede desgastar poco a poco.", ghostGate: "La Puerta Fantasma se asocia con intuición aguda y pensamientos repetitivos. Bien canalizada, puede volverse percepción creativa." },
      explain: { eyebrow: "Una entrada visual", title: "¿Es tu primera carta Saju? Empieza por la forma, el color y el papel de cada parte.", pillarsTitle: "Cuatro Pilares", pillarsBody: "Cada pilar tiene un signo del cielo y otro de la tierra. El Maestro del Día es el centro; los demás símbolos se leen en relación con él.", elementsTitle: "Cinco Elementos", elementsBody: "Los elementos se convierten en estados de ánimo, hábitos, estilos de trabajo, necesidades afectivas y ritmos. El color permite ver el equilibrio de un vistazo.", linksTitle: "Relaciones de la carta", linksBody: "Estas relaciones ayudan a entender dónde la vida fluye, se tensa, atrae o repite un patrón." },
      element: { wood: "Madera", fire: "Fuego", earth: "Tierra", metal: "Metal", water: "Agua", growth: "crecer", spark: "impulso", ground: "base", edge: "decisión", flow: "fluidez" },
      link: { combination: "Combinación", clash: "Choque", harm: "Daño", penalty: "Castigo", ghostGate: "Puerta Fantasma" },
      glossary: { eyebrow: "Traducción integrada", title: "Primero el término técnico; enseguida, una explicación clara.", manseTitle: "Calendario Manse", manseBody: "El sistema que convierte los datos de nacimiento en los pilares de año, mes, día y hora.", dayMasterBody: "El signo celeste del Pilar del Día y el punto de referencia de toda la lectura.", wealthTitle: "Riqueza estable", wealthBody: "Ingresos regulares, presupuesto, bienes tangibles, fiabilidad y manejo práctico de recursos.", resourceTitle: "Recurso místico", resourceBody: "Intuición, aprendizaje poco común, análisis profundo, imaginación privada y pensamientos recurrentes.", needleTitle: "Estrella Aguja", needleBody: "Observación precisa y lenguaje incisivo, útiles en trabajos técnicos o minuciosos.", nobleTitle: "Noble celestial", nobleBody: "Mentores, ayuda oportuna y apoyo que suele aparecer cuando hace falta.", comboBody: "Dos signos cooperan y, en ciertas condiciones, pueden inclinarse hacia otro elemento.", clashBody: "Fuerzas opuestas que pueden verse como conflicto, movimiento, distancia o un cambio necesario." },
      trust: { eyebrow: "Con los límites claros", title: "Una tradición coreana para reflexionar, no un veredicto científico.", body: "SajuPop explica cómo se calcula la carta, protege tus datos y evita certezas médicas, legales, psicológicas o financieras.", item1: "Cálculo según el lugar de nacimiento", item2: "Explicaciones claras", item3: "Contexto cultural", item4: "Sin mensajes fatalistas", item5: "Cartas guardadas en privado" },
      bottom: { home: "Inicio", add: "Nueva", shop: "Lecturas", learn: "Aprender", account: "Cuenta" },
      loading: { eyebrow: "Leyendo tu carta", title: "Empezamos por el lugar y la hora en que naciste.", intro: "Primero levantamos la carta Manse. Después buscamos los patrones que merecen palabras cuidadosas.", estimate: "Suele tardar", estimateValue: "1-3 minutos", elapsed: "Tiempo", seconds: "s", stage1: "Corregir la hora de nacimiento", stage2: "Levantar los Cuatro Pilares", stage3: "Seguir los patrones de la carta", stage4: "Escribir la interpretación", stage5: "Cuidar el tono", long: "Esta lectura está tardando un poco más, pero sigue en marcha. Estamos afinando las últimas frases." },
      result: { eyebrow: "Tu lectura", ready: "Tu lectura SajuPop está lista.", overview: "En breve", chart: "Tu carta", reading: "Lectura completa", actions: "Pequeñas acciones", seen: "Lo que queremos reconocer primero", pattern: "Patrón central", move: "Prueba esto primero", center: "Centro de la carta", elementBalance: "Equilibrio de elementos", plain: "En palabras cotidianas", strongest: "Más fuerte", quietest: "Más suave", helpful: "Puede ayudar", location: "Lugar de nacimiento", noLinks: "No hay una relación dominante en la carta", why: "Por qué aparece esta lectura", actionsTitle: "Pequeñas cosas que pueden ayudar", saveTitle: "Guárdala solo si te apetece volver a ella.", saveBody: "Inicia sesión únicamente para guardar, desbloquear el informe completo o comprar créditos.", saveCta: "Entrar y guardar", disclaimer: "Saju es un sistema tradicional de interpretación para la reflexión y el entretenimiento. Esta lectura no sustituye consejos médicos, legales, financieros ni psicológicos.", retryTitle: "La lectura se detuvo antes de terminar.", retry: "Intentar de nuevo", noData: "Faltan datos de nacimiento", noDataTitle: "Empieza por tus datos de nacimiento.", noDataBody: "Necesitamos fecha, hora y lugar para levantar la carta.", start: "Ir a datos de nacimiento", marker: "Marcador de la carta", loudQuiet: "lo que destaca y lo que pide cuidado", remedy: "hábitos que facilitan vivir esta energía", relation: "por qué algo puede sentirse fluido, tenso, magnético o repetitivo", groupSelf: "Comprender tu patrón interior", groupChoices: "Decisiones en la vida real", groupRelationships: "Tu manera de relacionarte", groupDirection: "Entorno y próximos pasos", categoryCore: "Temperamento central", categoryElements: "Equilibrio de los cinco elementos", categoryIdentity: "Identidad y criterio interior", categoryBlindSpot: "Un patrón que conviene vigilar", categoryEffort: "Esfuerzo que merece reconocimiento", categoryPersonality: "Personalidad y emoción", categoryCareer: "Carrera y trabajo", categoryMoney: "Dinero y recursos", categoryLove: "Amor e intimidad", categoryFamily: "Familia y límites", categoryFriends: "Amistades y vida social", categoryEnvironment: "Entorno y estilo de vida", categoryPractice: "Experimentos prácticos" },
      account: { eyebrow: "Tu espacio SajuPop", title: "Tus lecturas, cuando quieras volver a ellas.", body: "Puedes leer sin cuenta. Inicia sesión solo para guardar una carta, pagar o conservar tu historial.", loginTitle: "Guardar para después", loginBody: "Cuando una lectura merezca quedarse, usa Google o correo electrónico.", vault: "Archivo de lecturas", vaultBody: "Aquí estarán tus cartas guardadas y los informes desbloqueados.", wallet: "Cartera de créditos", walletBody: "Los créditos Estrella y Luna aparecerán aquí cuando se conecte el pago.", privacy: "Perfil privado", privacyBody: "Cada cuenta solo puede ver su propio registro y sus datos guardados.", credits: "Créditos", starCredits: "Créditos Estrella", moonCredits: "Créditos Luna", creditsBody: "Los créditos se actualizan aquí después del pago.", membership: "Membresía", membershipBody: "Tu plan y los métodos de acceso conectados.", plan: "Plan", providers: "Acceso", saved: "Lecturas guardadas", vaultEmpty: "Tus lecturas guardadas aparecerán aquí.", signOut: "Cerrar sesión" },
      errors: { generic: "Algo salió mal. Inténtalo de nuevo.", config: "El acceso está conectado, pero Firebase Authentication aún no está habilitado.", method: "Este método de acceso todavía no está habilitado.", popup: "La ventana de acceso fue bloqueada. Permite ventanas emergentes e inténtalo de nuevo.", domain: "Esta dirección de prueba aún no está autorizada para Google.", credentials: "El correo o la contraseña no coinciden.", exists: "Este correo ya tiene una cuenta. Prueba a iniciar sesión." }
    },
    ja: {
      global: { homeSubtitle: "四柱推命リーディング", readingSubtitle: "鑑定ルーム", accountSubtitle: "マイページ", language: "言語" },
      nav: { readings: "メニュー", chart: "命式", glossary: "用語", trust: "ご案内", newChart: "新しい命式", readingRoom: "鑑定ルーム" },
      auth: { login: "ログイン", account: "アカウント", eyebrow: "会員ログイン", title: "この鑑定を残したいときだけ、ログインしてください。", note: "Googleまたはメールで続けられます。", google: "Googleで続ける", email: "メール", password: "パスワード", signIn: "ログイン", create: "アカウント作成", reset: "パスワード再設定", close: "ログインを閉じる", opening: "Googleログインを開いています...", resetSent: "パスワード再設定メールを送りました。", emailFirst: "先にメールを入力してください。", passwordFirst: "パスワードを入力してください。" },
      home: { eyebrow: "出生情報 -> 補正した命式 -> 自分にしっくりくる言葉", title: "韓国の四柱を、難しいままにしない鑑定です。", intro: "生年月日、出生時刻、出生地から四柱を出し、十神や神殺、五行の関係を日々の感覚に結びつけて丁寧に読み解きます。", proofChart: "万年暦で算出", proofVoice: "自然な言葉", proofPrivacy: "非公開が基本" },
      form: { title: "出生情報", correctionReady: "出生地補正つき", name: "名前", date: "生年月日", time: "出生時刻", country: "出生国", city: "出生都市", cityPlaceholder: "都市名を入力", calendar: "暦", gregorian: "新暦", lunar: "旧暦", unknown: "不明", accuracy: "時刻の精度", exact: "正確", approximate: "だいたい", unknownTime: "時刻不明", correctionIncluded: "出生地に合わせて補正します", correctionNote: "国と都市を選ぶだけで大丈夫です。時差などは裏側で計算します。", continue: "命式を読む" },
      products: { eyebrow: "鑑定を選ぶ", title: "気軽に始めても、内容はきちんと。", birthTitle: "$0.99 生まれ持った命式", birthBody: "性格、仕事、お金、恋愛、家族、合う環境、すぐできるヒントまで。", oneStar: "スター 1個", unlock: "ログインして開く", compatTitle: "相性リーディング", compatBody: "恋人、友人、仕事仲間、ルームメイトなど、さまざまな関係に。", compare: "ログインして比べる", cycleTitle: "10年運", cycleBody: "進む時、休む時、移る時、積み上げる時を大きな流れで見ます。", partlyFree: "一部無料", open: "ログインして見る", dateTitle: "吉日を選ぶ", dateBody: "引っ越し、結婚、契約、開業など大切な予定に合う日を探します。", pick: "ログインして選ぶ", yearTitle: "一年の運勢", yearBody: "一年のテーマ、月ごとの流れ、負荷がかかる時期と動きやすい時期。", view: "ログインして見る", askTitle: "鑑定に質問", askBody: "レポートを読んだあと、気になることを自分の言葉で聞けます。", oneMoon: "ムーン 1個", askCta: "ログインして質問" },
      filters: { all: "すべて", saju: "四柱", timing: "運勢・日取り", ask: "相談", basics: "基本", stars: "神殺", links: "関係" },
      chart: { eyebrow: "万年暦の命式", title: "解釈の前に、命式そのものを見ておきましょう。", meta: "出生情報から、SajuPopはこの形の命式を出します。", tapTerm: "気になる印を押すと、普段の言葉で意味が読めます。" },
      pillar: { hour: "時柱", day: "日柱", month: "月柱", year: "年柱", private: "内側の自分", identity: "自分の中心", social: "社会での役割", roots: "家系と土台", inner: "内面", center: "中心", season: "社会", origin: "ルーツ" },
      terms: { dayMaster: "日主", hiddenStems: "蔵干", tenGods: "通変星", stars: "神殺", harm: "子未の害", ghostGate: "鬼門" },
      termHelp: { dayMaster: "日主は命式の中心です。仕事、お金、恋愛、プレッシャー、助けも日主との関係から読みます。", hiddenStems: "蔵干は地支の内側にある気です。すぐには見えにくい感情や資質を表します。", tenGods: "通変星は、自分、仲間、表現、お金、責任、圧力、支えなどの関係を示す呼び名です。", stars: "神殺は、魅力、移動、助け、鋭い感覚、感情の強さなど、命式に細かな質感を加えます。", harm: "害は静かなずれを表します。冲ほど激しくなくても、少しずつ疲れがたまることがあります。", ghostGate: "鬼門は鋭い直感や考えが巡りやすい傾向と結びつきます。うまく使えば、深い洞察になります。" },
      explain: { eyebrow: "目でわかる入口", title: "四柱が初めてなら、役割・色・形から見てみましょう。", pillarsTitle: "四つの柱", pillarsBody: "それぞれの柱に天干と地支があります。日主を中心に、ほかの印との関係を読みます。", elementsTitle: "五行", elementsBody: "五行は気分、習慣、働き方、関係で必要なもの、時期の流れとして現れます。色で強弱をつかめます。", linksTitle: "命式の関係", linksBody: "合、冲、害、刑などから、流れやすい所、緊張する所、繰り返しやすい所を見ます。" },
      element: { wood: "木", fire: "火", earth: "土", metal: "金", water: "水", growth: "成長", spark: "情熱", ground: "安定", edge: "決断", flow: "感受性" },
      link: { combination: "合", clash: "冲", harm: "害", penalty: "刑", ghostGate: "鬼門" },
      glossary: { eyebrow: "用語をその場で翻訳", title: "専門用語のすぐ隣に、わかる言葉を置きました。", manseTitle: "万年暦", manseBody: "出生情報を年柱、月柱、日柱、時柱に換算する暦です。", dayMasterBody: "日柱の天干で、命式全体を読む基準になります。", wealthTitle: "正財", wealthBody: "安定した収入、予算、実物資産、信頼性、現実的な資源管理。", resourceTitle: "偏印", resourceBody: "直感、独特な学び方、深い分析、一人の想像、考えすぎやすさ。", needleTitle: "懸針殺", needleBody: "細かな観察と鋭い言葉。技術や精密さが必要な仕事で強みになります。", nobleTitle: "天乙貴人", nobleBody: "必要なときに現れる助け、指導者、タイミングのよい機会。", comboBody: "二つの印が協力し、条件によって別の五行へ傾くことがあります。", clashBody: "向かい合う力で、衝突だけでなく移動、距離、必要な変化を表すことがあります。" },
      trust: { eyebrow: "境界もきちんと", title: "自分を振り返るための韓国の伝統で、科学的な判定ではありません。", body: "SajuPopは計算の考え方を示し、出生情報を慎重に扱います。医療、法律、心理、金銭について断定しません。", item1: "出生地を反映した計算", item2: "普段の言葉で説明", item3: "文化的な背景も紹介", item4: "不安をあおる断定なし", item5: "非公開の保存データ" },
      bottom: { home: "ホーム", add: "命式追加", shop: "メニュー", learn: "用語", account: "マイページ" },
      loading: { eyebrow: "命式を読んでいます", title: "生まれた場所と時刻から、ゆっくり合わせていきます。", intro: "まず命式を出し、何度も重なる流れを探します。最後に、受け取りやすい言葉へ整えます。", estimate: "目安", estimateValue: "1〜3分", elapsed: "経過", seconds: "秒", stage1: "出生時刻を補正", stage2: "四柱を作成", stage3: "命式の流れを確認", stage4: "項目ごとの鑑定を作成", stage5: "言葉を丁寧に整える", long: "少し時間がかかっていますが、止まってはいません。最後の言葉を整えています。" },
      result: { eyebrow: "あなたの鑑定", ready: "SajuPopの鑑定ができました。", overview: "先に見ること", chart: "命式", reading: "詳しい鑑定", actions: "小さなヒント", seen: "最初に受け止めたいこと", pattern: "中心の流れ", move: "まず試すこと", center: "命式の中心", elementBalance: "五行バランス", plain: "普段の言葉では", strongest: "強い気", quietest: "静かな気", helpful: "助けになる気", location: "出生地", noLinks: "目立つ関係の印はありません", why: "この読み方の根拠", actionsTitle: "無理なくできる小さなこと", saveTitle: "また読みたいと思った鑑定だけ、残しておけます。", saveBody: "保存、全文の解放、クレジット購入のときだけログインしてください。", saveCta: "ログインして保存", disclaimer: "四柱推命は内省と娯楽のための伝統的な解釈体系です。医療、法律、金融、心理の助言に代わるものではありません。", retryTitle: "鑑定が完成する前に止まりました。", retry: "もう一度試す", noData: "出生情報がありません", noDataTitle: "出生情報から始めてください。", noDataBody: "命式を作るには生年月日、時刻、場所が必要です。", start: "出生情報を入力", marker: "命式の印", loudQuiet: "強く出る所と手当てが必要な所", remedy: "この気を扱いやすくする習慣", relation: "流れ、緊張、引力、繰り返しが生まれる理由", groupSelf: "内面の流れを知る", groupChoices: "現実での選び方", groupRelationships: "人との関わり方", groupDirection: "生活環境と次の方向", categoryCore: "中心となる気質", categoryElements: "五行のバランス", categoryIdentity: "自分の軸と内面", categoryBlindSpot: "見落としやすい点", categoryEffort: "積み重ねてきた努力", categoryPersonality: "性格と感情", categoryCareer: "進路と仕事", categoryMoney: "お金と資源", categoryLove: "恋愛と親密さ", categoryFamily: "家族と境界", categoryFriends: "対人関係", categoryEnvironment: "環境と暮らし", categoryPractice: "実践のヒント" },
      account: { eyebrow: "SajuPop マイページ", title: "また読みたいときに、いつでも戻れます。", body: "アカウントなしで先に読めます。保存、決済、履歴を残すときだけログインしてください。", loginTitle: "あとで読み返す", loginBody: "残したい鑑定ができたら、Googleかメールでログインしてください。", vault: "鑑定保管庫", vaultBody: "保存した命式と解放したレポートをここにまとめます。", wallet: "クレジット", walletBody: "決済をつなぐと、スターとムーンの残高がここに表示されます。", privacy: "非公開プロフィール", privacyBody: "各アカウントは自分の会員情報と保存データだけを見られます。", credits: "クレジット", starCredits: "スタークレジット", moonCredits: "ムーンクレジット", creditsBody: "決済が完了すると、ここに残高が反映されます。", membership: "会員情報", membershipBody: "プランとログイン方法を確認できます。", plan: "プラン", providers: "ログイン方法", saved: "保存した鑑定", vaultEmpty: "保存した鑑定はここに表示されます。", signOut: "ログアウト" },
      errors: { generic: "問題が起きました。もう一度お試しください。", config: "ログインは接続されていますが、Firebase Authenticationがまだ有効ではありません。", method: "このログイン方法はまだ有効ではありません。", popup: "ログイン画面がブロックされました。ポップアップを許可してもう一度お試しください。", domain: "このテスト用アドレスはGoogleログインの許可ドメインに入っていません。", credentials: "メールまたはパスワードが一致しません。", exists: "このメールは登録済みです。ログインをお試しください。" }
    }
  };

  const localeAliases = { zh: "zh-CN", "zh-Hans": "zh-CN", "zh-SG": "zh-CN", ko: "ko", es: "es", ja: "ja", en: "en" };

  function normalizeLocale(value) {
    if (!value) return "en";
    if (messages[value]) return value;
    const base = value.split("-")[0];
    return localeAliases[value] || localeAliases[base] || "en";
  }

  function getLocale() {
    return normalizeLocale(localStorage.getItem("sajupop.locale") || navigator.language);
  }

  function getPath(source, key) {
    return key.split(".").reduce((value, part) => value?.[part], source);
  }

  function t(key, variables = {}, locale = getLocale()) {
    const template = getPath(messages[normalizeLocale(locale)], key) ?? getPath(messages.en, key) ?? key;
    return String(template).replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? `{${name}}`);
  }

  function applyTranslations(root = document) {
    const locale = getLocale();
    document.documentElement.lang = locale;
    root.querySelectorAll("[data-i18n]").forEach((node) => {
      node.textContent = t(node.dataset.i18n, {}, locale);
    });
    root.querySelectorAll("[data-i18n-placeholder]").forEach((node) => {
      node.placeholder = t(node.dataset.i18nPlaceholder, {}, locale);
    });
    root.querySelectorAll("[data-language-selector]").forEach((select) => {
      select.value = locale;
    });
    document.dispatchEvent(new CustomEvent("sajupop-locale-applied", { detail: { locale } }));
  }

  function setLocale(locale) {
    const normalized = normalizeLocale(locale);
    localStorage.setItem("sajupop.locale", normalized);
    applyTranslations();
    window.dispatchEvent(new CustomEvent("sajupop-locale-changed", { detail: { locale: normalized } }));
  }

  document.addEventListener("change", (event) => {
    const selector = event.target.closest("[data-language-selector]");
    if (selector) setLocale(selector.value);
  });

  window.SajuPopI18n = { messages, getLocale, setLocale, t, applyTranslations, normalizeLocale };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", () => applyTranslations());
  else applyTranslations();
})();
